import Link from "next/link";
import { notFound } from "next/navigation";
import { CircleDollarSign, ExternalLink, MailWarning, ShoppingBag, Ticket } from "lucide-react";
import { createClient } from "@/shared/database/server";
import { formatEventDate, formatMoney } from "@/shared/lib/format";
import { EventCoverUpload } from "@/modules/events/ui/forms";
import { publishEvent } from "@/modules/events/application/actions";
import { EventCover } from "@/modules/events/ui/event-cover";
import { EventStatusBadge } from "@/modules/events/ui/event-status-badge";
import { AvailabilityIndicator } from "@/modules/events/ui/availability-indicator";
import { TicketTypeEditor } from "@/modules/events/ui/ticket-type-editor";
import { ResendTicketsButton } from "@/modules/ticketing/ui/resend-tickets-button";
import type { TicketDeliveryStatus } from "@/shared/database/types";

export default async function EventDetailPage({ params, searchParams }: { params: Promise<{ eventId: string }>; searchParams: Promise<{ error?: string; published?: string; delivery?: string }> }) {
  const { eventId } = await params; const query = await searchParams; const supabase = await createClient();
  const [{ data: event }, { data: ticketTypes }, { data: holds }, { data: metricsData }, { data: sales }] = await Promise.all([supabase.from("events").select("*").eq("id", eventId).single(), supabase.from("ticket_types").select("*").eq("event_id", eventId).order("sort_order"), supabase.from("ticket_holds").select("quantity").eq("event_id", eventId).eq("status", "active").gt("expires_at", new Date().toISOString()), supabase.rpc("get_event_ticket_metrics", { target_event: eventId }), supabase.rpc("get_event_ticket_sales", { target_event: eventId })]);
  if (!event) notFound(); const { data: venue } = await supabase.from("venues").select("*").eq("id", event.venue_id).single(); if (!venue) notFound(); const inventory = (ticketTypes ?? []).reduce((sum, type) => sum + type.quantity, 0); const reserved = (holds ?? []).reduce((sum, hold) => sum + hold.quantity, 0);
  const ticketMetrics = metricsData?.[0] ?? { tickets_issued: 0, paid_orders: 0, delivery_failures: 0 };
  return <><section className="card overflow-hidden"><div className="relative"><EventCover src={event.cover_image_url} alt={`Flyer de ${event.name}`} className="aspect-[16/7] min-h-64" priority/><EventStatusBadge status={event.status} className="absolute left-5 top-5"/></div><div className="grid gap-7 p-5 sm:p-7 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow">{formatEventDate(event.starts_at, venue.timezone)}</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">{event.name}</h1><p className="mt-2 text-neutral-500">{venue.name} · {venue.city}</p></div><div className="flex flex-wrap items-start gap-3">{event.status === "published" && <Link target="_blank" href={`/e/${event.slug}`} className="btn btn-secondary">Ver página <ExternalLink size={17}/></Link>}<EventCoverUpload organizationId={event.organization_id} eventId={event.id}/></div></div></section>
  {query.error && <p className="mt-6 rounded-xl border border-orange-900 bg-orange-950/30 p-4 text-sm text-orange-200">No se pudo publicar: revisá que la fecha sea futura y el inventario no supere la capacidad.</p>}{query.published && <p className="mt-6 rounded-xl border border-lime-900 bg-lime-950/30 p-4 text-sm text-lime-200">Evento publicado. Ya podés compartirlo.</p>}
  {query.delivery === "sent" && <p className="mt-6 rounded-xl border border-lime-900 bg-lime-950/30 p-4 text-sm text-lime-200">Acceso reenviado correctamente.</p>}{query.delivery === "failed" && <p className="mt-6 rounded-xl border border-orange-900 bg-orange-950/30 p-4 text-sm text-orange-200">No se pudo reenviar. La compra y las entradas siguen válidas; podés reintentar.</p>}
  <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="card p-5"><p className="text-xs font-bold uppercase tracking-wider text-neutral-600">Reservas</p><div className="mt-4"><AvailabilityIndicator reserved={reserved} capacity={event.capacity}/></div></div><Metric label="Entradas emitidas" value={String(ticketMetrics.tickets_issued)}/><Metric label="Ventas pagadas" value={String(ticketMetrics.paid_orders)}/><Metric label="Capacidad configurada" value={`${inventory} / ${event.capacity}`}/></section>
  <section className="mt-10 grid items-start gap-6 lg:grid-cols-[1fr_420px]"><div><p className="eyebrow">La fecha</p><h2 className="section-title mt-2">Información</h2><div className="card mt-4 divide-y divide-white/[.06]"><Row label="Cuándo" value={formatEventDate(event.starts_at, venue.timezone)}/><Row label="Dónde" value={`${venue.name} · ${venue.address}, ${venue.city}`}/><Row label="Documento" value={event.require_document ? "Se solicita DNI" : "No se solicita DNI"}/></div>{event.description && <div className="card mt-4 p-5"><p className="text-sm leading-7 text-neutral-400">{event.description}</p></div>}</div><div><div className="flex items-center gap-2"><Ticket size={18} className="text-[var(--accent)]"/><h2 className="section-title">Entradas</h2></div><div className="mt-4"><TicketTypeEditor organizationId={event.organization_id} eventId={event.id} ticketTypes={ticketTypes ?? []} editable={event.status === "draft"}/></div></div></section>
  <section className="mt-12"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Ventas</p><h2 className="section-title mt-2">Entradas emitidas</h2></div>{ticketMetrics.delivery_failures > 0 && <span className="flex items-center gap-2 text-xs font-bold text-amber-300"><MailWarning size={15}/>{ticketMetrics.delivery_failures} envío pendiente</span>}</div>{sales?.length ? <div className="mt-4 grid gap-3">{sales.map((sale) => <article className="card grid gap-5 p-5 lg:grid-cols-[1fr_1fr_auto] lg:items-center" key={sale.order_id}><div><div className="flex items-center gap-2"><ShoppingBag size={15} className="text-[var(--accent)]"/><p className="font-bold">Compra #{sale.order_public_id.slice(0, 8).toUpperCase()}</p><span className="rounded-full bg-[var(--accent)]/10 px-2 py-1 text-[10px] font-black uppercase text-[var(--accent)]">{sale.order_status === "paid" ? "Pagada" : "Reembolsada"}</span></div><p className="mt-2 text-sm text-neutral-400">{sale.buyer_name}</p><p className="mt-1 text-xs text-neutral-600">{sale.buyer_email}</p></div><div><p className="text-sm font-bold">{sale.ticket_count} {sale.ticket_count === 1 ? "entrada" : "entradas"}</p><p className="mt-1 text-xs text-neutral-500">{sale.ticket_names || "Emisión pendiente"}</p><p className="mt-2 flex items-center gap-1.5 text-xs font-bold text-neutral-500"><CircleDollarSign size={13}/>{formatMoney(sale.total_amount, sale.currency)} · {deliveryLabel(sale.delivery_status)}</p></div><div>{sale.order_status === "paid" && sale.ticket_count > 0 && <ResendTicketsButton orderId={sale.order_id} eventId={event.id}/>}</div></article>)}</div> : <div className="card mt-4 p-8 text-center"><ShoppingBag className="mx-auto text-neutral-700" size={30}/><h3 className="mt-4 font-black">Todavía no hay ventas pagadas</h3><p className="mt-2 text-sm text-neutral-500">Las compras confirmadas aparecerán acá con su emisión y entrega.</p></div>}</section>
  {event.status === "draft" && <form action={publishEvent} className="sticky bottom-20 mt-6 md:bottom-4"><input type="hidden" name="eventId" value={event.id}/><button className="btn btn-primary w-full shadow-2xl">Publicar evento</button></form>}</>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="card p-4"><p className="text-xs font-bold uppercase text-neutral-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="grid gap-1 p-5 sm:grid-cols-[120px_1fr]"><span className="text-xs font-bold uppercase tracking-wider text-neutral-600">{label}</span><span className="text-sm text-neutral-300">{value}</span></div>; }
function deliveryLabel(status: TicketDeliveryStatus | null) { if (status === "sent") return "Email enviado"; if (status === "failed") return "Email falló"; if (status === "processing") return "Enviando email"; return "Email pendiente"; }
