import Link from "next/link";
import { notFound } from "next/navigation";
import { ExternalLink, Ticket } from "lucide-react";
import { createClient } from "@/shared/database/server";
import { formatEventDate } from "@/shared/lib/format";
import { EventCoverUpload } from "@/modules/events/ui/forms";
import { publishEvent } from "@/modules/events/application/actions";
import { EventCover } from "@/modules/events/ui/event-cover";
import { EventStatusBadge } from "@/modules/events/ui/event-status-badge";
import { AvailabilityIndicator } from "@/modules/events/ui/availability-indicator";
import { TicketTypeEditor } from "@/modules/events/ui/ticket-type-editor";

export default async function EventDetailPage({ params, searchParams }: { params: Promise<{ eventId: string }>; searchParams: Promise<{ error?: string; published?: string }> }) {
  const { eventId } = await params; const query = await searchParams; const supabase = await createClient();
  const [{ data: event }, { data: ticketTypes }, { data: holds }] = await Promise.all([supabase.from("events").select("*").eq("id", eventId).single(), supabase.from("ticket_types").select("*").eq("event_id", eventId).order("sort_order"), supabase.from("ticket_holds").select("quantity").eq("event_id", eventId).eq("status", "active").gt("expires_at", new Date().toISOString())]);
  if (!event) notFound(); const { data: venue } = await supabase.from("venues").select("*").eq("id", event.venue_id).single(); if (!venue) notFound(); const inventory = (ticketTypes ?? []).reduce((sum, type) => sum + type.quantity, 0); const reserved = (holds ?? []).reduce((sum, hold) => sum + hold.quantity, 0);
  return <><section className="card overflow-hidden"><div className="relative"><EventCover src={event.cover_image_url} alt={`Flyer de ${event.name}`} className="aspect-[16/7] min-h-64" priority/><EventStatusBadge status={event.status} className="absolute left-5 top-5"/></div><div className="grid gap-7 p-5 sm:p-7 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow">{formatEventDate(event.starts_at, venue.timezone)}</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">{event.name}</h1><p className="mt-2 text-neutral-500">{venue.name} · {venue.city}</p></div><div className="flex flex-wrap items-start gap-3">{event.status === "published" && <Link target="_blank" href={`/e/${event.slug}`} className="btn btn-secondary">Ver página <ExternalLink size={17}/></Link>}<EventCoverUpload organizationId={event.organization_id} eventId={event.id}/></div></div></section>
  {query.error && <p className="mt-6 rounded-xl border border-orange-900 bg-orange-950/30 p-4 text-sm text-orange-200">No se pudo publicar: revisá que la fecha sea futura y el inventario no supere la capacidad.</p>}{query.published && <p className="mt-6 rounded-xl border border-lime-900 bg-lime-950/30 p-4 text-sm text-lime-200">Evento publicado. Ya podés compartirlo.</p>}
  <section className="mt-6 grid gap-4 md:grid-cols-[1.4fr_1fr_1fr]"><div className="card p-5"><p className="text-xs font-bold uppercase tracking-wider text-neutral-600">Reservas</p><div className="mt-4"><AvailabilityIndicator reserved={reserved} capacity={event.capacity}/></div></div><Metric label="Capacidad" value={String(event.capacity)}/><Metric label="Entradas configuradas" value={String(inventory)}/></section>
  <section className="mt-10 grid items-start gap-6 lg:grid-cols-[1fr_420px]"><div><p className="eyebrow">La fecha</p><h2 className="section-title mt-2">Información</h2><div className="card mt-4 divide-y divide-white/[.06]"><Row label="Cuándo" value={formatEventDate(event.starts_at, venue.timezone)}/><Row label="Dónde" value={`${venue.name} · ${venue.address}, ${venue.city}`}/><Row label="Documento" value={event.require_document ? "Se solicita DNI" : "No se solicita DNI"}/></div>{event.description && <div className="card mt-4 p-5"><p className="text-sm leading-7 text-neutral-400">{event.description}</p></div>}</div><div><div className="flex items-center gap-2"><Ticket size={18} className="text-[var(--accent)]"/><h2 className="section-title">Entradas</h2></div><div className="mt-4"><TicketTypeEditor organizationId={event.organization_id} eventId={event.id} ticketTypes={ticketTypes ?? []} editable={event.status === "draft"}/></div></div></section>
  {event.status === "draft" && <form action={publishEvent} className="sticky bottom-20 mt-6 md:bottom-4"><input type="hidden" name="eventId" value={event.id}/><button className="btn btn-primary w-full shadow-2xl">Publicar evento</button></form>}</>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="card p-4"><p className="text-xs font-bold uppercase text-neutral-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="grid gap-1 p-5 sm:grid-cols-[120px_1fr]"><span className="text-xs font-bold uppercase tracking-wider text-neutral-600">{label}</span><span className="text-sm text-neutral-300">{value}</span></div>; }
