import { notFound } from "next/navigation";
import { LockKeyhole } from "lucide-react";
import { createClient } from "@/shared/database/server";
import { formatMoney } from "@/shared/lib/format";
import { EventCover } from "@/modules/events/ui/event-cover";
import { HoldCountdown } from "@/modules/orders/ui/hold-countdown";

type OrderItem = { name: string; quantity: number; unit_price_amount: number };
export default async function PendingOrderPage({ params }: { params: Promise<{ publicId: string }> }) {
  const { publicId } = await params; const supabase = await createClient(); const { data } = await supabase.rpc("get_public_order", { target_public_id: publicId }); const order = data?.[0]; if (!order) notFound();
  const items = order.items as unknown as OrderItem[];
  const expired = order.status === "expired";
  return <main className="container-shell grid min-h-screen place-items-center py-6 sm:py-10"><section className="w-full max-w-2xl"><header className="mb-6 flex items-center justify-between"><span className="text-sm font-black tracking-[-.03em]">NIGHTLIFE OS</span><span className="flex items-center gap-1.5 text-xs text-neutral-600"><LockKeyhole size={13}/> Reserva segura</span></header><div className="card overflow-hidden"><EventCover src={order.event_cover_url} alt={`Flyer de ${order.event_name}`} className="aspect-[16/7]" priority/><div className="p-5 sm:p-8"><p className="eyebrow">Reserva temporal</p><h1 className="mt-3 text-3xl font-black tracking-[-.045em] sm:text-4xl">{expired ? "La reserva ya no está activa" : "Tu entrada está reservada"}</h1><p className="mt-3 text-sm leading-6 text-neutral-500">{expired ? "Las entradas se liberaron automáticamente para otros compradores." : "Completá la compra antes de que termine el tiempo."}</p><div className="mt-6"><HoldCountdown expiresAt={order.expires_at} eventSlug={order.event_slug} initiallyExpired={expired}/></div><div className="mt-7"><h2 className="text-lg font-bold">{order.event_name}</h2><div className="mt-4 grid gap-3">{items.map((item, index) => <div className="flex justify-between text-sm" key={`${item.name}-${index}`}><span className="text-neutral-400">{item.quantity}× {item.name}</span><span>{formatMoney(item.quantity * item.unit_price_amount, order.currency)}</span></div>)}</div><div className="mt-5 grid gap-2 border-t border-white/[.08] pt-5 text-sm"><Row label="Entradas" value={formatMoney(order.subtotal_amount, order.currency)}/><Row label="Cargo de servicio" value={formatMoney(order.service_fee_amount, order.currency)}/><Row label="Total" value={formatMoney(order.total_amount, order.currency)} strong/></div></div>{process.env.NODE_ENV === "development" && <details className="mt-7 rounded-xl border border-white/[.06] p-4 text-xs text-neutral-600"><summary className="cursor-pointer font-bold">Información de desarrollo</summary><p className="mt-3 leading-5">FASE 1 termina en reserva activa. El cobro y la emisión de entradas se incorporan en FASE 2; no se simuló un pago aprobado.</p></details>}</div></div></section></main>;
}
function Row({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <div className={`flex justify-between ${strong ? "mt-1 text-lg font-black text-white" : "text-neutral-400"}`}><span>{label}</span><span>{value}</span></div>; }
