"use client";

import { useActionState, useState } from "react";
import { CreditCard, MapPin, MonitorSmartphone, PackagePlus, Plus, Power, Store, Wallet, X } from "lucide-react";
import { addProductsToEvent, createPosDevice, createSalesLocation, revokePosDevice, updateEventProduct } from "../application/actions";
import { formatMoney } from "@/shared/lib/format";
import { ActionMessage } from "@/shared/ui/action-message";
import { SubmitButton } from "@/shared/ui/submit-button";
import { StatCard } from "@/shared/ui/stat-card";
import { EmptyState } from "@/shared/ui/empty-state";

type CatalogProduct = { id: string; name: string; category_id: string | null; default_price_amount: number | null; currency: string; active: boolean };
type EventProduct = { id: string; product_id: string; price_amount: number; currency: string; enabled: boolean; sort_order: number };
type Location = { id: string; name: string; description: string; active: boolean; sort_order: number };
type Device = { id: string; sales_location_id: string; name: string; status: "pending" | "active" | "revoked"; code_expires_at: string; activated_at: string | null };
type PosSession = { id: string; sales_location_id: string; pos_device_id: string; status: "open" | "closed"; operator_label: string | null; opening_cash_amount: number; closing_difference_amount: number | null; opened_at: string; closed_at: string | null };

export function EventPosManagement({ eventId, products, eventProducts, locations, locationProductIds, devices, sessions, overview, locationMetrics, productMetrics }: {
  eventId: string; products: CatalogProduct[]; eventProducts: EventProduct[]; locations: Location[];
  locationProductIds: Record<string, string[]>; devices: Device[]; sessions: PosSession[];
  overview: { total_revenue: number; sale_count: number; cash_revenue: number; card_revenue: number; mercado_pago_revenue: number; bank_transfer_revenue: number; open_sessions: number; currency: string };
  locationMetrics: Array<{ sales_location_id: string; location_name: string; revenue: number; sale_count: number; device_count: number }>;
  productMetrics: Array<{ product_id: string; product_name: string; quantity_sold: number; revenue: number }>;
}) {
  const [addProductsOpen, setAddProductsOpen] = useState(false); const [locationOpen, setLocationOpen] = useState(false); const [deviceLocation, setDeviceLocation] = useState<string | null>(null);
  const productById = new Map(products.map((product) => [product.id, product]));
  const assigned = new Set(eventProducts.map((item) => item.product_id));
  const availableProducts = products.filter((product) => product.active && product.default_price_amount !== null && !assigned.has(product.id));
  return <>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <StatCard icon={Wallet} tone="emerald" label="Ventas" value={formatMoney(overview.total_revenue, overview.currency)}/>
      <StatCard icon={CreditCard} tone="blue" label="Operaciones" value={String(overview.sale_count)}/>
      <StatCard icon={Wallet} tone="amber" label="Efectivo" value={formatMoney(overview.cash_revenue, overview.currency)}/>
      <StatCard icon={Store} tone="violet" label="Cajas abiertas" value={String(overview.open_sessions)}/>
    </section>
    <section className="card mt-7 p-5 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Catálogo de la fecha</p><h2 className="section-title mt-2">Productos y precios</h2></div><button className="btn btn-secondary" onClick={() => setAddProductsOpen(true)} disabled={!availableProducts.length}><PackagePlus size={17}/>Agregar productos</button></div>{eventProducts.length ? <div className="mt-6 grid gap-3">{eventProducts.map((eventProduct) => { const product = productById.get(eventProduct.product_id); if (!product) return null; return <EventProductRow key={eventProduct.id} eventId={eventId} item={eventProduct} name={product.name}/>; })}</div> : <div className="mt-6"><EmptyState icon={CreditCard} title="Todavía no hay productos" description="Agregá productos del catálogo de tu organización para comenzar."/></div>}</section>
    <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Operación</p><h2 className="section-title mt-2">Puntos de venta</h2></div><button className="btn btn-primary" onClick={() => setLocationOpen(true)} disabled={!eventProducts.length}><Plus size={17}/>Punto de venta</button></div>{locations.length ? <div className="mt-5 grid gap-4 lg:grid-cols-2">{locations.map((location) => { const metric = locationMetrics.find((item) => item.sales_location_id === location.id); const locationDevices = devices.filter((device) => device.sales_location_id === location.id); const locationSessions = sessions.filter((session) => session.sales_location_id === location.id); return <article className="card p-5" key={location.id}><div className="flex items-start justify-between gap-3"><div><MapPin size={18} className="text-[var(--accent)]"/><h3 className="mt-3 text-xl font-black">{location.name}</h3><p className="mt-1 text-sm text-neutral-500">{location.description || `${locationProductIds[location.id]?.length ?? 0} productos`}</p></div><span className="text-right"><strong className="block">{formatMoney(metric?.revenue ?? 0, overview.currency)}</strong><small className="text-neutral-600">{metric?.sale_count ?? 0} ventas</small></span></div><div className="mt-5 border-t border-[var(--border)] pt-4"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider text-neutral-600">Dispositivos</p><button className="btn btn-ghost min-h-9 px-3 text-xs" onClick={() => setDeviceLocation(location.id)}><Plus size={14}/>Agregar</button></div>{locationDevices.length ? <div className="mt-3 grid gap-2">{locationDevices.map((device) => <div className="flex items-center justify-between gap-3 rounded-xl border border-[var(--border)] p-3" key={device.id}><div><p className="text-sm font-bold">{device.name}</p><p className="text-xs text-neutral-600">{device.status === "pending" ? "Esperando activación" : device.status === "active" ? "Activo" : "Revocado"}</p></div>{device.status !== "revoked" && <form action={revokePosDevice}><input type="hidden" name="eventId" value={eventId}/><input type="hidden" name="deviceId" value={device.id}/><button className="btn btn-ghost btn-icon text-red-300" aria-label={`Revocar ${device.name}`}><Power size={15}/></button></form>}</div>)}</div> : <p className="mt-3 text-sm text-neutral-600">Sin dispositivos.</p>}{locationSessions.length > 0 && <p className="mt-4 text-xs text-neutral-500">{locationSessions.filter((session) => session.status === "open").length} cajas abiertas · {locationSessions.filter((session) => session.status === "closed").length} cierres históricos</p>}</div></article>; })}</div> : <div className="mt-5"><EmptyState icon={Store} title="Creá tu primer punto de venta" description="Puede ser una barra, un stand, una caja exterior o cualquier ubicación operativa."/></div>}</section>
    {productMetrics.length > 0 && <section className="card mt-7 p-5 sm:p-7"><p className="eyebrow">Resultados</p><h2 className="section-title mt-2">Más vendidos</h2><div className="mt-5 divide-y divide-[var(--border)]">{productMetrics.map((metric) => <div className="flex items-center justify-between py-4" key={metric.product_id}><div><p className="font-bold">{metric.product_name}</p><p className="text-xs text-neutral-500">{metric.quantity_sold} unidades</p></div><strong>{formatMoney(metric.revenue, overview.currency)}</strong></div>)}</div></section>}
    {addProductsOpen && <AddProductsDialog eventId={eventId} products={availableProducts} onClose={() => setAddProductsOpen(false)}/>}
    {locationOpen && <LocationDialog eventId={eventId} eventProducts={eventProducts.map((item) => ({ id: item.id, name: productById.get(item.product_id)?.name ?? "Producto" }))} onClose={() => setLocationOpen(false)}/>}
    {deviceLocation && <DeviceDialog eventId={eventId} locationId={deviceLocation} onClose={() => setDeviceLocation(null)}/>}
  </>;
}

function EventProductRow({ eventId, item, name }: { eventId: string; item: EventProduct; name: string }) { const [state, action] = useActionState(updateEventProduct, {}); return <form action={action} className="grid gap-3 rounded-xl border border-[var(--border)] p-4 sm:grid-cols-[1fr_150px_auto] sm:items-end"><input type="hidden" name="eventId" value={eventId}/><input type="hidden" name="eventProductId" value={item.id}/><div><p className="font-black">{name}</p><label className="mt-2 flex items-center gap-2 text-xs text-neutral-500"><input type="hidden" name="enabled" value="false"/><input type="checkbox" name="enabled" value="true" defaultChecked={item.enabled}/>Habilitado esta fecha</label></div><label className="label">Precio ARS<input className="field h-11" name="pricePesos" type="number" min="0" step="1" defaultValue={item.price_amount / 100}/></label><SubmitButton className="btn btn-secondary min-h-11">Guardar</SubmitButton><div className="sm:col-span-3"><ActionMessage message={state.error}/><ActionMessage message={state.success} tone="success"/></div></form>; }

function AddProductsDialog({ eventId, products, onClose }: { eventId: string; products: CatalogProduct[]; onClose: () => void }) { const [state, action] = useActionState(addProductsToEvent, {}); return <Dialog title="Agregar productos" onClose={onClose}><form action={action} className="grid gap-4"><input type="hidden" name="eventId" value={eventId}/><div className="grid max-h-80 gap-2 overflow-y-auto">{products.map((product) => <label className="flex min-h-14 items-center justify-between gap-3 rounded-xl border border-[var(--border)] p-3" key={product.id}><span><strong className="block text-sm">{product.name}</strong><small className="text-neutral-500">{formatMoney(product.default_price_amount!, product.currency)}</small></span><input name="productIds" value={product.id} type="checkbox" className="size-5"/></label>)}</div><ActionMessage message={state.error}/><ActionMessage message={state.success} tone="success"/><SubmitButton className="btn btn-primary min-h-14">Agregar seleccionados</SubmitButton></form></Dialog>; }

function LocationDialog({ eventId, eventProducts, onClose }: { eventId: string; eventProducts: Array<{ id: string; name: string }>; onClose: () => void }) { const [state, action] = useActionState(createSalesLocation, {}); return <Dialog title="Nuevo punto de venta" onClose={onClose}><form action={action} className="grid gap-4"><input type="hidden" name="eventId" value={eventId}/><label className="label">Nombre<input className="field" name="name" placeholder="Barra principal" required autoFocus/></label><label className="label">Descripción <span className="font-normal text-neutral-600">(opcional)</span><input className="field" name="description"/></label><fieldset><legend className="label">Productos</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{eventProducts.map((product) => <label className="flex min-h-12 items-center gap-3 rounded-xl border border-[var(--border)] p-3 text-sm font-bold" key={product.id}><input type="checkbox" name="eventProductIds" value={product.id} defaultChecked/>{product.name}</label>)}</div></fieldset><ActionMessage message={state.error}/><ActionMessage message={state.success} tone="success"/><SubmitButton className="btn btn-primary min-h-14"><Store size={17}/>Crear punto</SubmitButton></form></Dialog>; }

function DeviceDialog({ eventId, locationId, onClose }: { eventId: string; locationId: string; onClose: () => void }) { const [state, action] = useActionState(createPosDevice, {}); return <Dialog title="Agregar dispositivo" onClose={onClose}><form action={action} className="grid gap-4"><input type="hidden" name="eventId" value={eventId}/><input type="hidden" name="locationId" value={locationId}/><label className="label">Nombre<input className="field" name="name" placeholder="Caja 2" required autoFocus/></label><ActionMessage message={state.error}/><ActionMessage message={state.success} tone="success"/>{state.pin && <div className="rounded-2xl border border-[var(--accent)]/30 bg-[var(--accent)]/[.06] p-5 text-center"><p className="text-xs font-black uppercase tracking-widest text-neutral-500">Código de activación</p><p className="mt-3 font-mono text-4xl font-black tracking-[.25em]">{state.pin.slice(0, 3)} {state.pin.slice(3)}</p><p className="mt-3 text-xs text-neutral-500">Ingresalo en /pos. Es single-use y vence en 30 minutos.</p></div>}<SubmitButton className="btn btn-primary min-h-14"><MonitorSmartphone size={17}/>Generar PIN</SubmitButton></form></Dialog>; }

function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-end bg-black/70 backdrop-blur-sm sm:items-center sm:justify-center sm:p-5" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="max-h-[92dvh] w-full overflow-y-auto rounded-t-3xl border border-[var(--border)] bg-[var(--surface)] p-5 sm:max-w-xl sm:rounded-3xl sm:p-7" role="dialog" aria-modal="true"><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-black">{title}</h2><button className="btn btn-ghost btn-icon" onClick={onClose} aria-label="Cerrar"><X size={18}/></button></div>{children}</section></div>; }
