"use client";

import { useEffect, useMemo, useState } from "react";
import { Banknote, Check, CreditCard, Minus, Plus, Search, Settings2, Store, WalletCards, WifiOff, X } from "lucide-react";
import { ThemeToggle } from "@/shared/ui/theme-toggle";
import { EnpassLogo } from "@/shared/ui/brand";
import { formatMoney } from "@/shared/lib/format";
import { addCartItem, calculateCartTotal, paymentMethodLabels, setCartQuantity, type PosCatalogItem, type PosCartLine, type PosDeviceSessionView, type PosPaymentMethod } from "../domain/pos";

type CashSummary = { opening_cash_amount: number; cash_sales_amount: number; cash_in_amount: number; cash_out_amount: number; cash_refunds_amount: number; expected_cash_amount: number; sale_count: number; total_sales_amount: number };
type SaleResult = { order_public_id: string; sale_code: string; total_amount: number; currency: string; payment_method: PosPaymentMethod; cash_received_amount: number | null; change_amount: number; reused: boolean };

export function PosShell({ initialSession, initialCatalog, initialCashSummary }: { initialSession: PosDeviceSessionView | null; initialCatalog: PosCatalogItem[]; initialCashSummary: CashSummary | null }) {
  const [session, setSession] = useState(initialSession); const [catalog, setCatalog] = useState(initialCatalog); const [cashSummary, setCashSummary] = useState(initialCashSummary);
  async function refresh() { const response = await fetch("/api/pos/session", { cache: "no-store" }); if (!response.ok) { setSession(null); setCatalog([]); setCashSummary(null); return; } const body = await response.json() as { session: PosDeviceSessionView; catalog: PosCatalogItem[]; cashSummary: CashSummary | null }; setSession(body.session); setCatalog(body.catalog); setCashSummary(body.cashSummary); }
  if (!session) return <ActivationScreen onActivated={(value) => { setSession(value); void refresh(); }}/>;
  if (session.cash_session_status !== "open") return <OpenCashScreen session={session} onOpened={() => void refresh()}/>;
  return <ActivePos session={session} catalog={catalog} cashSummary={cashSummary} onRefresh={refresh} onEnded={() => { setSession(null); setCatalog([]); setCashSummary(null); }}/>;
}

function ActivationScreen({ onActivated }: { onActivated: (session: PosDeviceSessionView) => void }) {
  const [pin, setPin] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(null); try { const response = await fetch("/api/pos/activate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ pin }) }); const body = await response.json() as { session?: PosDeviceSessionView; error?: string }; if (!response.ok || !body.session) { setError(body.error ?? "No pudimos activar la caja."); return; } onActivated(body.session); } catch { setError("Sin conexión. Revisá la red."); } finally { setPending(false); } }
  return <main className="mx-auto flex min-h-dvh max-w-md flex-col px-5 py-7"><div className="flex items-center justify-between"><EnpassLogo/><ThemeToggle/></div><div className="my-auto py-12"><span className="grid size-16 place-items-center rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><Store size={28}/></span><p className="eyebrow mt-8">Activar caja</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">Prepará este dispositivo.</h1><p className="mt-4 text-sm leading-6 text-neutral-500">Ingresá el código temporal generado desde el evento. No necesitás una cuenta de productor.</p><form className="mt-8 grid gap-4" onSubmit={submit}><label className="label">Código de 6 dígitos<input className="field h-16 text-center font-mono text-3xl font-black tracking-[.3em]" value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="one-time-code" placeholder="000000" autoFocus/></label>{error && <p className="status-danger rounded-xl p-3 text-sm font-bold">{error}</p>}<button className="btn btn-primary min-h-14" disabled={pending || pin.length !== 6}>{pending ? "Activando…" : "Activar caja"}</button></form></div><p className="text-center text-xs text-neutral-600">Sesión segura · acceso limitado al punto de venta</p></main>;
}

function OpenCashScreen({ session, onOpened }: { session: PosDeviceSessionView; onOpened: () => void }) {
  const [openingPesos, setOpeningPesos] = useState("0"); const [operator, setOperator] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(null); try { const response = await fetch("/api/pos/open", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ openingCashAmount: Math.round(Number(openingPesos) * 100), operatorLabel: operator }) }); const body = await response.json() as { error?: string }; if (!response.ok) { setError(body.error ?? "No pudimos abrir la caja."); return; } onOpened(); } catch { setError("Sin conexión. No se abrió la caja."); } finally { setPending(false); } }
  return <main className="mx-auto flex min-h-dvh max-w-lg flex-col px-5 py-7"><div className="flex items-center justify-between"><EnpassLogo/><ThemeToggle/></div><div className="my-auto card p-6 sm:p-8"><p className="eyebrow">{session.sales_location_name}</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">{session.device_name}</h1><p className="mt-3 text-sm text-neutral-500">{session.event_name}</p><form className="mt-8 grid gap-5" onSubmit={submit}><label className="label">Fondo inicial<input className="field h-14 text-xl font-black" value={openingPesos} onChange={(event) => setOpeningPesos(event.target.value)} type="number" min="0" step="1" inputMode="numeric" required/></label><label className="label">Cajero <span className="font-normal text-neutral-600">(opcional)</span><input className="field" value={operator} onChange={(event) => setOperator(event.target.value)} maxLength={80} placeholder="Lucas"/></label>{error && <p className="status-danger rounded-xl p-3 text-sm font-bold">{error}</p>}<button className="btn btn-primary min-h-14" disabled={pending || Number(openingPesos) < 0}>{pending ? "Abriendo…" : "Abrir caja"}</button></form></div></main>;
}

function ActivePos({ session, catalog, cashSummary, onRefresh, onEnded }: { session: PosDeviceSessionView; catalog: PosCatalogItem[]; cashSummary: CashSummary | null; onRefresh: () => Promise<void>; onEnded: () => void }) {
  const [cart, setCart] = useState<PosCartLine[]>([]); const [category, setCategory] = useState("Todos"); const [search, setSearch] = useState(""); const [checkoutOpen, setCheckoutOpen] = useState(false); const [moreOpen, setMoreOpen] = useState(false); const [sale, setSale] = useState<SaleResult | null>(null); const [online, setOnline] = useState(true);
  useEffect(() => { const update = () => setOnline(navigator.onLine); update(); window.addEventListener("online", update); window.addEventListener("offline", update); return () => { window.removeEventListener("online", update); window.removeEventListener("offline", update); }; }, []);
  const categories = useMemo(() => ["Todos", ...Array.from(new Set(catalog.map((item) => item.category_name ?? "Otros")))], [catalog]);
  const filtered = catalog.filter((item) => (category === "Todos" || (item.category_name ?? "Otros") === category) && (!search || `${item.product_name} ${item.sku ?? ""} ${item.barcode ?? ""}`.toLowerCase().includes(search.toLowerCase())));
  const total = calculateCartTotal(cart);
  async function logout() { await fetch("/api/pos/logout", { method: "POST" }).catch(() => undefined); onEnded(); }
  if (sale) return <SaleComplete sale={sale} onNew={() => { setSale(null); setCart([]); setCheckoutOpen(false); void onRefresh(); }}/>;
  return <main className="min-h-dvh"><header className="sticky top-0 z-30 border-b border-[var(--border)] bg-[color:var(--background)]/95 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-black">{session.sales_location_name}</p><p className="truncate text-xs text-neutral-500">{session.device_name} · {session.event_name}</p></div><div className="flex items-center gap-2">{!online && <span className="flex items-center gap-1 text-xs font-bold text-red-400"><WifiOff size={15}/>Sin conexión</span>}<ThemeToggle/><button className="btn btn-ghost btn-icon" onClick={() => setMoreOpen(true)} aria-label="Gestión de caja"><Settings2 size={18}/></button></div></div></header><div className="mx-auto grid max-w-[1500px] gap-5 p-4 lg:grid-cols-[1fr_390px] lg:p-6"><section><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-neutral-600" size={18}/><input className="field h-14 pl-11" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar producto, SKU o código…"/></div><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{categories.map((item) => <button className={`min-h-11 shrink-0 rounded-full border px-4 text-sm font-bold ${category === item ? "border-[var(--foreground)] bg-[var(--foreground)] text-[var(--background)]" : "border-[var(--border)]"}`} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div>{filtered.length ? <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-4">{filtered.map((product) => <button className="card card-interactive flex min-h-36 flex-col justify-between p-4 text-left" onClick={() => setCart((current) => addCartItem(current, product))} key={product.event_product_id}><span className="text-lg font-black leading-tight">{product.product_name}</span><span className="mt-5 text-sm font-black">{formatMoney(product.price_amount, product.currency)}</span></button>)}</div> : <div className="card mt-4 p-10 text-center text-sm text-neutral-500">No encontramos productos.</div>}</section><Cart cart={cart} total={total} onChange={(id, quantity) => setCart((current) => setCartQuantity(current, id, quantity))} onCheckout={() => setCheckoutOpen(true)} online={online}/></div><div className="fixed inset-x-0 bottom-0 z-20 border-t border-[var(--border)] bg-[var(--background)] p-3 lg:hidden"><button className="btn btn-primary min-h-14 w-full" disabled={!cart.length || !online} onClick={() => setCheckoutOpen(true)}>{cart.reduce((sum, line) => sum + line.quantity, 0)} productos · {formatMoney(total, cart[0]?.currency ?? "ARS")}</button></div>{checkoutOpen && <CheckoutDialog cart={cart} total={total} online={online} onClose={() => setCheckoutOpen(false)} onSale={setSale}/>} {moreOpen && <CashManagement session={session} summary={cashSummary} onClose={() => setMoreOpen(false)} onRefresh={onRefresh} onClosed={() => void logout()}/>}</main>;
}

function Cart({ cart, total, onChange, onCheckout, online }: { cart: PosCartLine[]; total: number; onChange: (id: string, quantity: number) => void; onCheckout: () => void; online: boolean }) { return <aside className="card sticky top-24 hidden h-fit p-5 lg:block"><p className="eyebrow">Venta actual</p><h2 className="mt-2 text-2xl font-black">Carrito</h2>{cart.length ? <div className="mt-5 grid gap-3">{cart.map((line) => <div className="flex items-center justify-between gap-3 border-b border-[var(--border)] pb-3" key={line.event_product_id}><div><p className="font-bold">{line.product_name}</p><p className="text-xs text-neutral-500">{formatMoney(line.price_amount * line.quantity, line.currency)}</p></div><Quantity line={line} onChange={onChange}/></div>)}<div className="mt-2 flex items-end justify-between"><span className="text-sm font-bold text-neutral-500">TOTAL</span><strong className="text-3xl">{formatMoney(total, cart[0]?.currency ?? "ARS")}</strong></div><button className="btn btn-primary mt-3 min-h-14" onClick={onCheckout} disabled={!online}>{online ? "Cobrar" : "Sin conexión"}</button></div> : <p className="mt-8 text-sm text-neutral-500">Tocá un producto para agregarlo.</p>}</aside>; }
function Quantity({ line, onChange }: { line: PosCartLine; onChange: (id: string, quantity: number) => void }) { return <div className="flex items-center gap-1"><button className="grid size-10 place-items-center rounded-xl border border-[var(--border)]" onClick={() => onChange(line.event_product_id, line.quantity - 1)} aria-label={`Quitar ${line.product_name}`}><Minus size={15}/></button><span className="w-8 text-center font-black">{line.quantity}</span><button className="grid size-10 place-items-center rounded-xl border border-[var(--border)]" onClick={() => onChange(line.event_product_id, line.quantity + 1)} aria-label={`Agregar ${line.product_name}`}><Plus size={15}/></button></div>; }

function CheckoutDialog({ cart, total, online, onClose, onSale }: { cart: PosCartLine[]; total: number; online: boolean; onClose: () => void; onSale: (sale: SaleResult) => void }) {
  const [method, setMethod] = useState<PosPaymentMethod>("cash"); const [receivedPesos, setReceivedPesos] = useState(String(Math.ceil(total / 100))); const [reference, setReference] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const received = Math.round(Number(receivedPesos) * 100); const change = method === "cash" ? Math.max(0, received - total) : 0;
  async function charge() { if (!online || pending) return; setPending(true); setError(null); const idempotencyKey = crypto.randomUUID(); try { const response = await fetch("/api/pos/sale", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idempotencyKey, items: cart.map((line) => ({ event_product_id: line.event_product_id, quantity: line.quantity })), paymentMethod: method, cashReceivedAmount: method === "cash" ? received : null, externalReference: reference || null }) }); const body = await response.json() as { sale?: SaleResult; error?: string }; if (!response.ok || !body.sale) { setError(body.error ?? "No pudimos registrar la venta."); return; } onSale(body.sale); } catch { setError("Sin conexión. La venta no fue registrada."); } finally { setPending(false); } }
  return <Modal onClose={onClose}><div className="flex items-center justify-between"><div><p className="eyebrow">Cobrar</p><h2 className="mt-2 text-3xl font-black">{formatMoney(total, cart[0]?.currency ?? "ARS")}</h2></div><button className="btn btn-ghost btn-icon" onClick={onClose}><X/></button></div><div className="mt-6 grid grid-cols-2 gap-2">{(["cash", "card", "mercado_pago", "bank_transfer"] as const).map((item) => <button className={`min-h-20 rounded-xl border p-3 text-left text-sm font-black ${method === item ? "border-[var(--foreground)] bg-[var(--foreground)] text-[var(--background)]" : "border-[var(--border)]"}`} onClick={() => setMethod(item)} key={item}>{item === "cash" ? <Banknote size={18}/> : item === "card" ? <CreditCard size={18}/> : <WalletCards size={18}/>}<span className="mt-2 block">{paymentMethodLabels[item]}</span></button>)}</div>{method === "cash" ? <div className="mt-5 grid gap-3"><label className="label">Recibido<input className="field h-14 text-xl font-black" value={receivedPesos} onChange={(event) => setReceivedPesos(event.target.value)} type="number" min={Math.ceil(total / 100)} step="1"/></label><div className="flex items-center justify-between rounded-xl border border-[var(--border)] p-4"><span className="text-sm font-bold text-neutral-500">Cambio</span><strong className="text-xl">{formatMoney(change, cart[0]?.currency ?? "ARS")}</strong></div></div> : <label className="label mt-5">Referencia externa <span className="font-normal text-neutral-600">(opcional)</span><input className="field" value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Número de operación"/></label>}{method !== "cash" && <p className="mt-3 text-xs leading-5 text-neutral-500">Registro manual: confirmá únicamente después de verificar el cobro en la terminal o aplicación externa.</p>}{error && <p className="status-danger mt-4 rounded-xl p-3 text-sm font-bold">{error}</p>}<button className="btn btn-primary mt-5 min-h-14 w-full" onClick={() => void charge()} disabled={pending || !online || (method === "cash" && received < total)}>{pending ? "Registrando…" : `Confirmar ${paymentMethodLabels[method]}`}</button></Modal>;
}

function SaleComplete({ sale, onNew }: { sale: SaleResult; onNew: () => void }) { return <main className="grid min-h-dvh place-items-center p-5"><section className="w-full max-w-md text-center"><span className="mx-auto grid size-20 place-items-center rounded-full bg-[var(--foreground)] text-[var(--background)]"><Check size={38}/></span><p className="eyebrow mt-8">Venta #{sale.sale_code}</p><h1 className="mt-3 text-4xl font-black">Venta completada</h1><p className="mt-5 text-3xl font-black">{formatMoney(sale.total_amount, sale.currency)}</p><p className="mt-2 text-sm text-neutral-500">{paymentMethodLabels[sale.payment_method]}</p>{sale.payment_method === "cash" && <p className="mt-4 rounded-xl border border-[var(--border)] p-4 font-bold">Cambio {formatMoney(sale.change_amount, sale.currency)}</p>}<button className="btn btn-primary mt-8 min-h-14 w-full" onClick={onNew}>Nueva venta</button></section></main>; }

function CashManagement({ session, summary, onClose, onRefresh, onClosed }: { session: PosDeviceSessionView; summary: CashSummary | null; onClose: () => void; onRefresh: () => Promise<void>; onClosed: () => void }) {
  const [mode, setMode] = useState<"menu" | "movement" | "close">("menu"); const [movementType, setMovementType] = useState<"cash_in" | "cash_out">("cash_out"); const [amount, setAmount] = useState(""); const [reason, setReason] = useState(""); const [counted, setCounted] = useState(summary ? String(summary.expected_cash_amount / 100) : "0"); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function addMovement() { setPending(true); setError(null); try { const response = await fetch("/api/pos/movement", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: movementType, amount: Math.round(Number(amount) * 100), reason }) }); if (!response.ok) { setError("No pudimos registrar el movimiento."); return; } await onRefresh(); onClose(); } catch { setError("Sin conexión."); } finally { setPending(false); } }
  async function close() { setPending(true); setError(null); try { const response = await fetch("/api/pos/close", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ countedCashAmount: Math.round(Number(counted) * 100) }) }); if (!response.ok) { setError("No pudimos cerrar la caja."); return; } onClosed(); } catch { setError("Sin conexión."); } finally { setPending(false); } }
  return <Modal onClose={onClose}><div className="flex items-center justify-between"><div><p className="eyebrow">{session.device_name}</p><h2 className="mt-2 text-2xl font-black">Gestión de caja</h2></div><button className="btn btn-ghost btn-icon" onClick={onClose}><X/></button></div>{summary && <div className="mt-5 grid grid-cols-2 gap-2"><CashMetric label="Fondo inicial" value={summary.opening_cash_amount}/><CashMetric label="Ventas efectivo" value={summary.cash_sales_amount}/><CashMetric label="Ingresos" value={summary.cash_in_amount}/><CashMetric label="Retiros" value={-summary.cash_out_amount}/><div className="col-span-2 rounded-xl border border-[var(--border)] p-4"><p className="text-xs font-bold uppercase text-neutral-600">Efectivo esperado</p><p className="mt-2 text-2xl font-black">{formatMoney(summary.expected_cash_amount)}</p></div></div>}{mode === "menu" && <div className="mt-5 grid gap-2"><button className="btn btn-secondary min-h-12" onClick={() => setMode("movement")}>Ingreso o retiro</button><button className="btn btn-secondary min-h-12 text-red-300" onClick={() => setMode("close")}>Cerrar caja</button></div>}{mode === "movement" && <div className="mt-5 grid gap-4"><div className="grid grid-cols-2 gap-2"><button className={`btn ${movementType === "cash_in" ? "btn-primary" : "btn-secondary"}`} onClick={() => setMovementType("cash_in")}>Ingreso</button><button className={`btn ${movementType === "cash_out" ? "btn-primary" : "btn-secondary"}`} onClick={() => setMovementType("cash_out")}>Retiro</button></div><label className="label">Monto<input className="field" value={amount} onChange={(event) => setAmount(event.target.value)} type="number" min="1"/></label><label className="label">Razón<input className="field" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Caja central"/></label><button className="btn btn-primary min-h-14" onClick={() => void addMovement()} disabled={pending || Number(amount) <= 0 || reason.trim().length < 2}>Registrar</button></div>}{mode === "close" && <div className="mt-5 grid gap-4"><p className="text-sm leading-6 text-neutral-500">Contá el efectivo físico. La diferencia queda registrada y la sesión no se puede reabrir.</p><label className="label">Efectivo contado<input className="field h-14 text-xl font-black" value={counted} onChange={(event) => setCounted(event.target.value)} type="number" min="0"/></label><button className="btn btn-primary min-h-14" onClick={() => void close()} disabled={pending || Number(counted) < 0}>Confirmar cierre</button></div>}{error && <p className="status-danger mt-4 rounded-xl p-3 text-sm font-bold">{error}</p>}</Modal>;
}

function CashMetric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-[var(--border)] p-3"><p className="text-[10px] font-bold uppercase text-neutral-600">{label}</p><p className="mt-2 font-black">{formatMoney(value)}</p></div>; }
function Modal({ children, onClose }: { children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-end bg-black/70 backdrop-blur-sm sm:items-center sm:justify-center sm:p-5" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="max-h-[94dvh] w-full overflow-y-auto rounded-t-3xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-2xl sm:max-w-lg sm:rounded-3xl sm:p-7" role="dialog" aria-modal="true">{children}</section></div>; }
